#!/usr/bin/env python
#
# Copyright (c) 2016, Christian Schulz-Hanke
#
import sys
import os
try:
	import coala.starter
except:
	mypath = os.path.dirname(os.path.realpath(__file__))+"/"
	sys.path.append(mypath)
	mypath = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))+"/"
	sys.path.append(mypath)
	import coala.starter
	

if __name__ == "__main__":
	coala.starter.main(sys.argv[1:])

